version: '3'
services:
  exoframe_express_api:
    container_name: exoframe_express_api
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      labels:
        traefik.frontend.rule: 'Host:express.lndgrn.xyz'
    working_dir: /app
    depends_on:
      - exoframe_database
  exoframe_database:
    container_name: exoframe_postgres_db
    image: postgres:9.6
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 7772:5432
volumes:
  database:
