logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"

  [entryPoints.https]
  address = ":443"

  [entryPoints.https.tls]

  [entryPoints.traefik]
    address = ":8080"
    [entryPoints.traefik.auth.basic]
      users = ["test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/"]

[acme]
  email = "http@ludviglundgren.se"
  storage = "acme.json"
  entryPoint = "https"
  OnHostRule = true

[acme.httpChallenge]
  entryPoint = "http"

[docker]
  domain = "yourdomain.xyz"
  watch = true
  swarmmode = true

[api]
  entryPoint = "traefik"
  dashboard = true
